os: osx

git:
  submodules: false

before_script:
   - chmod +x .travis.install
   - ./.travis.install
   - git clone --depth 1 https://github.com/alexdobin/STAR
   - ls
   - cd STAR/source

script:
   -  make STARforMacStatic CXX=/usr/local/Cellar/gcc49/4.9.3/bin/g++-4.9

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git clone git@github.com:alexdobin/travis-tests1
  - cd travis-tests1
  - git config user.name alexdobin
  - git config user.email dobin@cshl.edu
  - cp ../STAR ./
  - git add STAR
  - git commit -m "STAR"
  - git push origin master
