 #os: osx

git:
  submodules: false

before_script:
   - chmod +x .travis.install
   #- ./.travis.install
   - git clone --depth 1 https://github.com/alexdobin/STAR STAR-compile
   - ls
   #- cd STAR/source

script:
   #-  make STARforMacStatic CXX=/usr/local/Cellar/gcc49/4.9.3/bin/g++-4.9
   - cp STAR-compile/bin/Linux_x86_64/STAR ./

after_success:
  - #cd ../..
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - #git remote add deploy DEPLOY_REPO_URI_GOES_HERE
  - #git push deploy
  - git clone git@github.com:alexdobin/travis-tests1
  - cd travis-tests1
  #- git config user.name alexdobin
  - cp ../STAR ./
  - git add STAR
  - git commit -m "STAR"
  - git push origin master
